added "download from the nexus" functionality
sbtqa/webdrivermanager pull request #1
Opened 2018-01-18 09:28 UTC by PavelAlennikov

2018-01-19 08:52 UTC, clicman requested changes

2018-01-19 08:52 UTC, clicman commented on src/main/java/io/github/bonigarcia/wdm/BrowserManager.java
> +            return urlParts[urlParts.length - 2];
Possible ArrayOutOfBoundsException

2018-01-19 08:52 UTC, clicman commented on src/main/java/io/github/bonigarcia/wdm/UrlFilter.java
>                          && !url.getFile().contains("32")) {
Move archs to constants. do not forgot to change all hardcode to constants

2018-01-19 09:59 UTC, PavelAlennikov commented on src/main/java/io/github/bonigarcia/wdm/BrowserManager.java
> +            return urlParts[urlParts.length - 2];
fixed

2018-01-23 06:13 UTC, 0I0u3uk commented on src/main/java/io/github/bonigarcia/wdm/BrowserManager.java
> +                                   String version) {
Fix formating

2018-01-23 06:13 UTC, 0I0u3uk commented on src/main/java/io/github/bonigarcia/wdm/BrowserManager.java
> +        }
this is gebbuging code?

2018-01-23 06:13 UTC, 0I0u3uk commented on src/main/java/io/github/bonigarcia/wdm/BrowserManager.java
> +        String driverStr = driverUrl.toString();
You are using this variable only in one place, maybe use driverUrl.toString() in this place?

2018-01-23 09:57 UTC, PavelAlennikov commented on src/main/java/io/github/bonigarcia/wdm/BrowserManager.java
> +                                   String version) {
solved

2018-01-23 09:57 UTC, PavelAlennikov commented on src/main/java/io/github/bonigarcia/wdm/BrowserManager.java
> +        }
solved

2018-01-26 07:01 UTC, PavelAlennikov commented
@clicman @0I0u3uk @SandraBarmina @kosteman 
guys changes are stable. You can review now

2018-01-26 07:16 UTC, 0I0u3uk approved these changes

2018-01-26 07:17 UTC, 0I0u3uk commented on src/main/resources/log4j.properties
> +log4j.rootLogger=DEBUG, consoleAppender, fileAppender
Релизить лучше с INFO я думаю, а то пользователь офигеет

2018-01-29 03:44 UTC, 0I0u3uk approved these changes

2018-01-29 04:14 UTC, kosteman requested changes

2018-01-29 04:14 UTC, kosteman commented on pom.xml
> +    <version>2.0.3-SNAPSHOT</version>
2.1-SNAPSHOT

2018-01-29 04:14 UTC, kosteman commented on src/main/java/io/github/bonigarcia/wdm/BrowserManager.java
> +        isUsingNexus = false;
usingNexus

2018-01-29 04:14 UTC, kosteman commented on src/main/java/io/github/bonigarcia/wdm/BrowserManager.java
> +    protected boolean isUsingNexus() {
protected boolean isUsingNexus() {
    return usingNexus;
}

2018-01-29 04:14 UTC, kosteman commented on src/main/java/io/github/bonigarcia/wdm/BrowserManager.java
> +    protected boolean isUsingNexus;
why these variables are not private?

2018-01-29 04:42 UTC, clicman approved these changes

2018-01-30 08:32 UTC, kosteman approved these changes

2018-01-30 08:33 UTC, merged